// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovV-spuggUOdwQPPIhJa28avr2THdZTk',
    appId: '1:342851368891:web:7b19ea17be2a6b1b9db69e',
    messagingSenderId: '342851368891',
    projectId: 'ecommercestore-7733c',
    authDomain: 'ecommercestore-7733c.firebaseapp.com',
    databaseURL: 'https://ecommercestore-7733c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommercestore-7733c.appspot.com',
    measurementId: 'G-9D05LX75XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3QSLkvn834F00DbDwrQB5IrGEDSnLi4',
    appId: '1:342851368891:android:b29507d46b7bf47d9db69e',
    messagingSenderId: '342851368891',
    projectId: 'ecommercestore-7733c',
    databaseURL: 'https://ecommercestore-7733c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommercestore-7733c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV30zIurBYSvJxyqNBCiT-DCvG7dx7WJE',
    appId: '1:342851368891:ios:37dcd7b8a92b7f7e9db69e',
    messagingSenderId: '342851368891',
    projectId: 'ecommercestore-7733c',
    databaseURL: 'https://ecommercestore-7733c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommercestore-7733c.appspot.com',
    androidClientId: '342851368891-kbm7h75e8d32p6hvgj1r74tofdc1u4r3.apps.googleusercontent.com',
    iosClientId: '342851368891-71fe9rjplr9re5ihos423b5fv19lscdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV30zIurBYSvJxyqNBCiT-DCvG7dx7WJE',
    appId: '1:342851368891:ios:37dcd7b8a92b7f7e9db69e',
    messagingSenderId: '342851368891',
    projectId: 'ecommercestore-7733c',
    databaseURL: 'https://ecommercestore-7733c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommercestore-7733c.appspot.com',
    androidClientId: '342851368891-kbm7h75e8d32p6hvgj1r74tofdc1u4r3.apps.googleusercontent.com',
    iosClientId: '342851368891-71fe9rjplr9re5ihos423b5fv19lscdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4FsHZXceT6ljVAaDZbT5x_DziK4drAg',
    appId: '1:342851368891:web:aa75d9e0402e5ab99db69e',
    messagingSenderId: '342851368891',
    projectId: 'ecommercestore-7733c',
    authDomain: 'ecommercestore-7733c.firebaseapp.com',
    databaseURL: 'https://ecommercestore-7733c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommercestore-7733c.appspot.com',
    measurementId: 'G-V7ZMBY593Y',
  );
}
